"use client";

import React, { useState, useEffect } from "react";
import { 
  Lightbulb, 
  Sparkles, 
  ArrowRight, 
  CheckCircle2, 
  X, 
  Loader2,
  Brain,
  Zap,
  TrendingDown,
  RefreshCcw,
  Plus
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

interface Insight {
  id: string;
  ai_suggestion: string;
  impact_predicted: number | null;
  status: "NEW" | "ACCEPTED" | "IGNORED";
  createdAt: string;
}

export default function InsightsPage() {
  const [insights, setInsights] = useState<Insight[]>([]);
  const [loading, setLoading] = useState(true);
  const [isRefreshing, setIsRefreshing] = useState(false);

  const fetchInsights = async () => {
    try {
      setLoading(true);
      const res = await fetch("/api/insights");
      if (res.ok) {
        setInsights(await res.json());
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleRefresh = async () => {
    setIsRefreshing(true);
    try {
        // Trigger a new AI Insight generation based on latest 7-day data
        // For now we'll just re-fetch, but in a real app we'd trigger the LLM
        const res = await fetch("/api/insights", {
            method: "POST",
            body: JSON.stringify({ activityData: [] }) // Real data would be passed here
        });
        if (res.ok) {
            await fetchInsights();
        }
    } catch (err) {
        console.error(err);
    } finally {
        setIsRefreshing(false);
    }
  };

  useEffect(() => {
    fetchInsights();
    window.addEventListener('activity-logged', fetchInsights);
    return () => window.removeEventListener('activity-logged', fetchInsights);
  }, []);

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <Loader2 className="w-8 h-8 text-primary animate-spin" />
      </div>
    );
  }

  return (
    <div className="space-y-10 animate-in fade-in duration-1000">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div>
          <h1 className="text-3xl font-bold text-foreground font-playfair tracking-tight">AI Coach Insights</h1>
          <p className="text-muted text-sm mt-1">Behavioral engineering strategy generated by the Neural Core.</p>
        </div>
        <button 
            onClick={handleRefresh}
            disabled={isRefreshing}
            className="flex items-center gap-2 bg-slate-900 text-white px-6 py-3 rounded-2xl font-bold text-xs hover:bg-slate-800 transition-all disabled:opacity-50 group"
        >
          {isRefreshing ? <Loader2 className="w-4 h-4 animate-spin text-primary" /> : <RefreshCcw className="w-4 h-4 text-primary group-hover:rotate-180 transition-transform duration-500" />}
          Neurological Refresh
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-6">
          <h3 className="text-xs font-bold text-muted uppercase tracking-[0.2em] mb-4">Neural Suggestions</h3>
          <AnimatePresence mode="popLayout">
            {insights.length === 0 && (
                <div className="p-12 text-center bg-gray-50 dark:bg-slate-800/50 rounded-[40px] border border-dashed border-gray-200 dark:border-slate-700">
                    <Brain className="w-12 h-12 text-muted/30 mx-auto mb-4" />
                    <p className="text-sm text-muted">Awaiting your first data streams to generate custom strategies...</p>
                </div>
            )}
            {insights.map((insight) => (
              <motion.div 
                key={insight.id}
                layout
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, scale: 0.9 }}
                className="bg-white/60 dark:bg-slate-800/60 backdrop-blur-xl p-8 rounded-[32px] border border-white/40 dark:border-slate-700/50 shadow-sm group hover:shadow-lg transition-all"
              >
                <div className="flex items-start justify-between mb-6">
                  <div className="w-10 h-10 rounded-xl bg-orange-500/10 flex items-center justify-center text-orange-500">
                    <Lightbulb className="w-5 h-5" />
                  </div>
                  {insight.impact_predicted && (
                    <div className="bg-success/10 text-success px-4 py-1.5 rounded-full text-[10px] font-bold uppercase tracking-widest border border-success/20 shadow-sm">
                        -{insight.impact_predicted}kg Potential
                    </div>
                  )}
                </div>
                
                <p className="text-sm text-foreground font-medium leading-relaxed mb-8 italic">
                  &quot;{insight.ai_suggestion}&quot;
                </p>

                <div className="flex items-center gap-3">
                   <button className="bg-slate-900 text-white px-6 py-2.5 rounded-xl text-[10px] font-bold hover:bg-slate-700 transition-all flex items-center gap-2">
                     Accept Strategy
                   </button>
                   <button className="p-2.5 hover:bg-red-50 dark:hover:bg-red-500/10 text-muted hover:text-red-500 rounded-xl transition-all">
                     <X className="w-4 h-4" />
                   </button>
                </div>
              </motion.div>
            ))}
          </AnimatePresence>
        </div>

        <div className="space-y-8">
           <div className="bg-gradient-to-br from-primary/10 to-primary/5 p-10 rounded-[40px] border border-primary/20 relative overflow-hidden group">
              <div className="absolute top-0 right-0 p-10 opacity-10 transition-transform group-hover:scale-125 rotate-12">
                <Brain className="w-48 h-48" />
              </div>
              <div className="relative z-10">
                 <h4 className="text-2xl font-playfair font-bold text-slate-900 dark:text-white mb-4">The Logic Guard Coach</h4>
                 <p className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed mb-8">
                    Our AI models analyze your unique lifestyle fingerprint to develop hyper-personalized mitigation pathways. By following these suggestions, you can reduce your annual budget debt by up to 25%.
                 </p>
                 <div className="space-y-4">
                    {[
                        "Precision-targeted Behavioral Shifts",
                        "Real-time Outcome Simulation",
                        "Contextual Substitution Logic"
                    ].map(feat => (
                        <div key={feat} className="flex items-center gap-3">
                            <div className="w-5 h-5 rounded-full bg-primary/20 flex items-center justify-center text-primary">
                                <CheckCircle2 className="w-3 h-3" />
                            </div>
                            <span className="text-xs font-bold text-slate-700 dark:text-slate-300">{feat}</span>
                        </div>
                    ))}
                 </div>
              </div>
           </div>

           <div className="bg-[#0f172a] text-white p-10 rounded-[40px] shadow-2xl relative overflow-hidden group">
              <div className="absolute top-[-20%] right-[-10%] opacity-10">
                 <Zap className="w-64 h-64 text-primary" />
              </div>
              <div className="relative z-10 space-y-6">
                 <div className="flex items-center gap-2 text-primary font-bold text-xs uppercase tracking-widest">
                    <Sparkles className="w-4 h-4" />
                    Neural Performance
                 </div>
                 <h4 className="text-xl font-bold italic">Coach Accuracy: 98.4%</h4>
                 <div className="flex items-center gap-10">
                    <div>
                        <span className="text-[10px] text-white/50 block font-bold uppercase tracking-widest">Verified Savings</span>
                        <span className="text-xl font-bold">142.5kg</span>
                    </div>
                    <div>
                        <span className="text-[10px] text-white/50 block font-bold uppercase tracking-widest">Growth Index</span>
                        <span className="text-xl font-bold text-success">+14%</span>
                    </div>
                 </div>
                 <p className="text-white/40 text-[10px] italic leading-tight">
                    *Calculated via Groq Llama 3 on your local Ledger trends.
                 </p>
              </div>
           </div>
        </div>
      </div>
    </div>
  );
}
